[graph]
all-features = true
all-targets = true

[advisories]
dbs = ["https://github.com/RustSec/advisory-db"]

[bans]
multiple-versions = "warn"

[licenses]
confidence-threshold = 0.8
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-DFS-2016"]

[sources]
denied = ["git"]
unknown-registry = "deny"
unknown-git = "deny"
